### PR TITLE
chore: upgrade to use latest version of phpstan

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Updates to latest version of laravel-phpstan, fixes new PHPstan errors

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
@alfonsobries can you test this on `ark.dev` to ensure we don't rely on overwriting any of the classes that are now made `final`?

**Comment by alfonsobries** [comment]
@ItsANameToo yeah test passes and the editor works fine. It creates some new issues with phpstan  but that can be handled on the PR we update this dependency

**Comment by alfonsobries** [comment]
@ItsANameToo Update: Thought you refer to `ark.io` so ignore my previous comment (actually ark.io already have some phpstan error but we are not checking them in github actions)

ill check `ark.dev` in a moment

**Comment by alfonsobries** [comment]
@ItsANameToo If you merge this new version into this PR it should work fine: https://github.com/ArkEcosystem/ark.dev/pull/191

**Comment by ItsANameToo** [comment]
@alfonsobries phpstan

**Comment by alfonsobries** [comment]
@ItsANameToo ✅

**Comment by faustbrian** [comment]
@alfonsobries conflicts

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
